import { createContext, useContext, useState, useEffect, type ReactNode } from 'react';

type Language = 'en' | 'ru';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  toggleLanguage: () => void;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

// Cловарь переводов
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.teams': 'Teams',
    'nav.players': 'Players',
    'nav.matches': 'Matches',
    'nav.analytics': 'Analytics',
    'nav.predict': 'Predict',
    'nav.history': 'History',
    'nav.admin': 'Admin',
    'nav.signIn': 'Sign In',
    'nav.logout': 'Logout',

    // Header
    'header.tagline': 'Basketball Intelligence For Matchups, History And Live Prediction Ops',
    'header.liveData': 'Live Data Sync',

    // Auth page
    'auth.title': 'Sign in with cleaner access and real workspace context.',
    'auth.subtitle': 'Authentication runs against the live backend, so sessions, prediction history and admin actions persist in the real app state.',
    'auth.secureWorkspace': 'Secure workspace access',
    'auth.accessLayer': 'Access layer',
    'auth.nodeApi': 'Node API + Postgres',
    'auth.workspaceGate': 'Workspace gate',
    'auth.signIn': 'Sign in',
    'auth.register': 'Register',
    'auth.signInContinue': 'Sign in and continue',
    'auth.createAccount': 'Create an account',
    'auth.emailOrLogin': 'Email or login',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.fullName': 'Full name',
    'auth.enterWorkspace': 'Enter workspace',
    'auth.createAndContinue': 'Create and continue',
    'auth.processing': 'Processing...',
    'auth.demoAccounts': 'Demo accounts',
    'auth.readyProfiles': '3 ready profiles',
    'auth.clickToFill': 'Click any card to fill the form instantly.',
    'auth.useDemo': 'Use demo',
    'auth.adminNote': 'Backups, audits and moderation tools',
    'auth.operatorNote': 'Schedule flow and prediction ops',
    'auth.userNote': 'History, saved runs and scouting views',
    'auth.enterPassword': 'Enter your password',
    'auth.createPassword': 'Create a secure password',
    'auth.signInHint': 'Use email or a short demo alias like admin, operator or user.',
    'auth.registerHint': 'Registration creates a real user in the backend and starts a live session immediately.',
    'auth.demoHint': 'Demo aliases work here too: enter admin, operator or user instead of the full email.',
    'auth.newAccountHint': 'New accounts are created with the standard user role and can start saving predictions immediately.',
    'auth.invalidCredentials': 'Invalid credentials. Try one of the demo accounts below.',
    'auth.registrationFailed': 'Registration could not be completed.',
    'auth.authFailed': 'Authentication failed.',

    // Features
    'feature.history': 'Persistent prediction history',
    'feature.historyDesc': 'Each run stays attached to the active account and appears in the private history feed.',
    'feature.workspace': 'Role-based workspace access',
    'feature.workspaceDesc': 'Admin, operator and user sessions unlock different parts of the platform cleanly.',
    'feature.auth': 'Live backend auth',
    'feature.authDesc': 'The screen talks to the real Node API and Postgres session flow, not a mocked frontend form.',

    // Home page
    'home.title': 'Cleaner match intelligence, less landing-page noise.',
    'home.subtitle': 'The home screen now works more like a sports hub: key metrics first, current matchup second, and the rest of the information split into clearer sections instead of one long decorative feed.',
    'home.connected': 'Connected stack',
    'home.liveBasketball': 'Live basketball workspace',
    'home.newPrediction': 'New prediction',
    'home.openSchedule': 'Open schedule',
    'home.featuredGame': 'Featured game',
    'home.preview': 'Preview',
    'home.final': 'Final',
    'home.noGame': 'No game loaded',
    'home.modelConfidence': 'Model confidence',
    'home.nextFixture': 'The next loaded fixture will appear here.',
    'home.accuracy': 'Accuracy',
    'home.teams': 'Teams',
    'home.games': 'Games',
    'home.samples': 'Samples',
    'home.modelValidation': 'model validation',
    'home.trackedProfiles': 'tracked profiles',
    'home.loadedFixtures': 'loaded fixtures',
    'home.historicalRecords': 'historical records',
    'home.notes': 'Notes',
    'home.predictionEngine': 'Prediction engine',
    'home.predictionEngineDesc': 'Historical sample size is stable and the prediction endpoint is responding through the live backend.',
    'home.scheduleWindow': 'Current schedule window',
    'home.scheduleWindowDesc': '{upcoming} upcoming games and {recent} finished games are available for browsing.',
    'home.navigationCleanup': 'Navigation cleanup',
    'home.navigationCleanupDesc': 'Instead of stacking everything vertically, the home page now separates schedule, team and prediction views into tabs.',
    'home.standingsSnapshot': 'Standings snapshot',
    'home.topTeams': 'Top teams',
    'home.fullStandings': 'Full standings',
    'home.overview': 'Overview',
    'home.schedule': 'Schedule',
    'home.predictions': 'Predictions',
    'home.recentUpcoming': 'Recent and upcoming games',
    'home.allGames': 'All games',
    'home.teamBoard': 'Team board',
    'home.leagueLeaders': 'League leaders',
    'home.teamIndex': 'Team index',
    'home.predictionLane': 'Prediction lane',
    'home.recentRuns': 'Recent model runs',
    'home.predictionWorkspace': 'Prediction workspace',
    'home.history': 'History',
    'home.noPredictions': 'You have not saved any prediction runs yet. Start with a matchup and the result will appear here and in history.',
    'home.signInPrompt': 'Sign in to save predictions, revisit results and compare model outputs over time.',

    // Teams page
    'teams.title': 'Standings and team identity in one tighter board.',
    'teams.subtitle': 'Compare teams quickly in standings view, then switch to cards when you want more visual detail.',
    'teams.board': 'Team board',
    'teams.clubsLoaded': '{count} clubs loaded',
    'teams.searchTeams': 'Search teams',
    'teams.searchPlaceholder': 'Boston, Atlantic, BOS...',
    'teams.view': 'View',
    'teams.standings': 'Standings',
    'teams.cards': 'Cards',
    'teams.conference': 'Conference',
    'teams.all': 'All',
    'teams.east': 'East',
    'teams.west': 'West',
    'teams.topRecord': 'Top record',
    'teams.leagueOffense': 'League offense',
    'teams.bestDifferential': 'Best differential',
    'teams.visibleTeams': 'Visible teams',
    'teams.noData': 'No data',
    'teams.averageAcross': 'Average across all seeded teams.',
    'teams.netPoints': '{value} net points',
    'teams.withinView': 'Within the current view.',
    'teams.rank': 'Rank',
    'teams.team': 'Team',
    'teams.record': 'Record',
    'teams.winRate': 'Win %',
    'teams.for': 'For',
    'teams.allowed': 'Allowed',
    'teams.net': 'Net',
    'teams.division': 'Division',

    // Players page
    'players.title': 'Player profiles with season switcher',
    'players.subtitle': 'Click any card to open the full profile where you can switch between seasons.',
    'players.searchPlaceholder': 'LeBron, Curry, Jokic...',
    'players.view': 'View',
    'players.cards': 'Cards',
    'players.board': 'Board',
    'players.topScorer': 'Top scorer',
    'players.topPlaymaker': 'Top playmaker',
    'players.averageScoring': 'Average scoring',
    'players.acrossSet': 'Across the current result set.',
    'players.clickPrompt': 'Click any card to open profile with season switcher.',
    'players.player': 'Player',
    'players.team': 'Team',
    'players.position': 'Pos',
    'players.openProfile': 'Open profile',

    // Matches page
    'matches.title': 'Schedule and results in one tighter slate view.',
    'matches.subtitle': 'Scan the slate, open a game for context, or jump into prediction workflows without fighting the layout.',
    'matches.board': 'Match board',
    'matches.gamesInFeed': '{count} games in the feed',
    'matches.filter': 'Filter board',
    'matches.allGames': 'All games',
    'matches.upcoming': 'Upcoming',
    'matches.finals': 'Finals',
    'matches.currentFocus': 'Current focus',
    'matches.allDesc': 'Showing the full slate with finished and scheduled matchups together.',
    'matches.upcomingDesc': 'Showing only upcoming games that are ready for previews and prediction flows.',
    'matches.finalsDesc': 'Showing final scores for quick review and comparison.',
    'matches.finished': 'Finished',
    'matches.finishedDesc': 'Games with a final score.',
    'matches.upcomingCount': 'Upcoming',
    'matches.upcomingCountDesc': 'Fixtures ready for previews.',
    'matches.currentView': 'Current view',
    'matches.selectedBoard': 'Selected board state.',
    'matches.visibleGames': 'Visible games',
    'matches.listedBelow': 'Currently listed below.',
    'matches.date': 'Date',
    'matches.matchup': 'Matchup',
    'matches.status': 'Status',
    'matches.score': 'Score',
    'matches.final': 'Final',
    'matches.scheduled': 'Scheduled',
    'matches.openDetail': 'Open detail',
    'matches.noMatches': 'No games match the current filter.',

    // Match detail page
    'match.backToSchedule': 'Back to schedule',
    'match.finalScore': 'Final score',
    'match.upcomingFixture': 'Upcoming fixture',
    'match.scoreline': 'Scoreline',
    'match.useAI': 'Use the AI engine for this matchup',
    'match.useAIDesc': 'Launch a probability run using the current team form and historical signal base already loaded into the backend.',
    'match.createPrediction': 'Create prediction',
    'match.notFound': 'Match not found.',
    'match.backToMatches': 'Back to matches',

    // Analytics page
    'analytics.title': 'One analytics workspace, split into clearer operating views.',
    'analytics.subtitle': 'Model quality, league context and schedule behavior now live in separate sections so the page reads more like an internal console and less like a wall of widgets.',
    'analytics.board': 'Analytics board',
    'analytics.loading': 'Loading analytics feed',
    'analytics.views': 'Views',
    'analytics.model': 'Model',
    'analytics.league': 'League',
    'analytics.schedule': 'Schedule',
    'analytics.modelDesc': 'Model view keeps the focus on health, factor mix and database coverage.',
    'analytics.leagueDesc': 'League view highlights contenders, offensive output and comparative team context.',
    'analytics.scheduleDesc': 'Schedule view surfaces game load and recently tracked fixtures.',
    'analytics.topTeam': 'Top team',
    'analytics.loadedGames': 'Loaded games',
    'analytics.trackedPlayers': 'Tracked players',
    'analytics.modelHealth': 'Model health',
    'analytics.predictionAccuracy': 'Prediction accuracy',
    'analytics.historicalDepth': 'Historical data depth',
    'analytics.rosterCoverage': 'Roster coverage',
    'analytics.scheduleReadiness': 'Schedule readiness',
    'analytics.modelVersion': 'Model version',
    'analytics.teamsConnected': 'Teams connected',
    'analytics.signalsTracked': 'Signals tracked',
    'analytics.healthSnapshot': 'Health snapshot',
    'analytics.factorDistribution': 'Model factor distribution',
    'analytics.contenderBoard': 'Contender win-rate board',
    'analytics.offensiveOutput': 'Offensive output by top teams',
    'analytics.scheduleIntensity': 'Schedule intensity across loaded matches',
    'analytics.unavailable': 'Unavailable',

    // Prediction pages
    'prediction.buildMatchup': 'Build a matchup and let the model work from real team context.',
    'prediction.engine': 'Matchup engine',
    'prediction.teamsAvailable': '{count} teams available',
    'prediction.historicalContext': 'Historical rows, recent form, roster quality and matchup context now flow together through the live prediction engine.',
    'prediction.preview': 'Preview',
    'prediction.homeSide': 'Home side',
    'prediction.awaySide': 'Away side',
    'prediction.selectTeam': 'Select a team',
    'prediction.waitingSelection': 'Waiting for selection',
    'prediction.chooseHome': 'Choose the home side',
    'prediction.chooseAway': 'Choose the away side',
    'prediction.pickBoth': 'Pick both teams before starting the model.',
    'prediction.differentTeams': 'Choose two different teams.',
    'prediction.savedToAccount': 'Prediction is saved to your account and scored by the hybrid model immediately.',
    'prediction.generate': 'Generate prediction',
    'prediction.running': 'Running model...',
    'prediction.signInRequired': 'Sign in to run private predictions.',
    'prediction.signInDesc': 'Predictions are stored against real user accounts, so you need an authenticated session before the model can save and return a result.',
    'prediction.unlock': 'Unlock prediction mode',
    'prediction.backToBuilder': 'Back to prediction builder',
    'prediction.notFound': 'Prediction not found.',
    'prediction.missingId': 'Prediction id is missing.',
    'prediction.aiResult': 'AI result',
    'prediction.confidence': '{value}% confidence',
    'prediction.modelLeans': 'The model leans toward {team} based on the current team profile, live roster signal and the trained historical signal mix.',
    'prediction.trainingRows': '{count} training rows',
    'prediction.expectedScore': 'Expected score',
    'prediction.modelSplit': 'Model split',

    // History page
    'history.title': 'Your prediction history.',
    'history.subtitle': 'Every run is tied to your account and available for quick review inside the app.',
    'history.savedRuns': 'Saved prediction runs',
    'history.items': '{count} items',
    'history.signInRequired': 'Your history becomes available after sign-in.',
    'history.signInDesc': 'Prediction history is tied to authenticated accounts and stored in the connected database.',
    'history.signIn': 'Sign in',
    'history.noPredictions': 'You have not created any predictions yet.',
    'history.startNew': 'Start a new run',

    // Admin page
    'admin.title': 'Admin tools grouped into a cleaner control room.',
    'admin.subtitle': 'Users, audits and backups stay in separate operational views so moderation and maintenance feel tighter and easier to scan.',
    'admin.restricted': 'Restricted workspace',
    'admin.createBackup': 'Create backup',
    'admin.creatingBackup': 'Creating backup...',
    'admin.reviewUsers': 'Review users',
    'admin.systemSnapshot': 'System snapshot',
    'admin.modelAccuracy': 'Model accuracy',
    'admin.backupsStored': 'Backups stored',
    'admin.lastBackup': 'Last backup',
    'admin.noBackups': 'No backups yet',
    'admin.overview': 'Overview',
    'admin.users': 'Users',
    'admin.auditLog': 'Audit log',
    'admin.backups': 'Backups',
    'admin.stackStatus': 'Stack status',
    'admin.teamsTracked': 'Teams tracked',
    'admin.matchesTracked': 'Matches tracked',
    'admin.playersTracked': 'Players tracked',
    'admin.predictionsTracked': 'Predictions tracked',
    'admin.quickActions': 'Quick actions',
    'admin.createNewBackup': 'Create new backup',
    'admin.openAuditLog': 'Open audit log',
    'admin.activeAccounts': 'Active accounts',
    'admin.blockedAccounts': 'Blocked accounts',
    'admin.user': 'User',
    'admin.role': 'Role',
    'admin.status': 'Status',
    'admin.action': 'Action',
    'admin.active': 'Active',
    'admin.blocked': 'Blocked',
    'admin.block': 'Block',
    'admin.unblock': 'Unblock',
    'admin.updating': 'Updating...',
    'admin.noUsers': 'No users were returned by the backend.',
    'admin.auditTimeline': 'Audit timeline',
    'admin.noEvents': 'No audit events were returned by the backend.',
    'admin.noDetails': 'No additional details were recorded.',
    'admin.actor': 'Actor',
    'admin.backupOperations': 'Backup operations',
    'admin.backupOpsDesc': 'Create restorable snapshots directly from the connected admin API.',
    'admin.createNewBackup': 'Create new backup',
    'admin.noBackupsAvailable': 'No backups are currently available.',
    'admin.backup': 'Backup',
    'admin.size': 'Size',
    'admin.restore': 'Restore',
    'admin.restoring': 'Restoring...',
    'admin.confirmRestore': 'Restore {filename}? This will overwrite the current database content.',
    'admin.backupCreated': 'Backup created: {filename}',
    'admin.backupFailed': 'Backup creation failed.',
    'admin.backupRestored': 'Backup restored: {filename}',
    'admin.restoreFailed': 'Backup restore failed.',
    'admin.userStatusUpdated': '{username} is now {status}.',
    'admin.statusUpdateFailed': 'User status update failed.',
    'admin.loadFailed': 'Failed to load admin data from the backend.',

    // 404 page
    'notfound.title': 'This page is off the board.',
    'notfound.subtitle': 'The route you requested is not available in the current build. Head back to the dashboard or jump into the scouting sections that are already connected to the live stack.',
    'notfound.backToDashboard': 'Back to dashboard',
    'notfound.exploreTeams': 'Explore teams',
    'notfound.routeMissing': '404 • route missing',

    // Footer
    'footer.copyright': '© 2026 Score Team',
    'footer.subscribe': 'Subscribe to us',
    'footer.copied': 'Copied!',
    'footer.email': 'Email',

    // Common
    'common.loading': 'Loading dashboard',
    'common.signIn': 'Sign in',
    'common.unavailable': 'Unavailable',
    'common.home': 'Home',
    'common.away': 'Away',
    'common.vs': 'VS',
    'common.tipoff': 'Tipoff',

    // Season
    'season.n_a': 'Season n/a',
  },
  ru: {
    // Navigation
    'nav.dashboard': 'Дашборд',
    'nav.teams': 'Команды',
    'nav.players': 'Игроки',
    'nav.matches': 'Матчи',
    'nav.analytics': 'Аналитика',
    'nav.predict': 'Прогноз',
    'nav.history': 'История',
    'nav.admin': 'Админ',
    'nav.signIn': 'Войти',
    'nav.logout': 'Выйти',

    // Header
    'header.tagline': 'Баскетбольная аналитика для матчей, истории и прогнозов',
    'header.liveData': 'Live Data Sync',

    // Auth page
    'auth.title': 'Вход с более чистым доступом и реальным контекстом рабочего пространства.',
    'auth.subtitle': 'Аутентификация работает с реальным бэкендом, поэтому сессии, история прогнозов и действия администратора сохраняются в реальном состоянии приложения.',
    'auth.secureWorkspace': 'Безопасный доступ',
    'auth.accessLayer': 'Уровень доступа',
    'auth.nodeApi': 'Node API + Postgres',
    'auth.workspaceGate': 'Вход в рабочее пространство',
    'auth.signIn': 'Войти',
    'auth.register': 'Регистрация',
    'auth.signInContinue': 'Войти и продолжить',
    'auth.createAccount': 'Создать аккаунт',
    'auth.emailOrLogin': 'Email или логин',
    'auth.email': 'Email',
    'auth.password': 'Пароль',
    'auth.fullName': 'Полное имя',
    'auth.enterWorkspace': 'Войти в рабочее пространство',
    'auth.createAndContinue': 'Создать и продолжить',
    'auth.processing': 'Обработка...',
    'auth.demoAccounts': 'Демо аккаунты',
    'auth.readyProfiles': '3 готовых профиля',
    'auth.clickToFill': 'Нажмите на карточку для мгновенного заполнения формы.',
    'auth.useDemo': 'Использовать',
    'auth.adminNote': 'Резервное копирование, аудит и инструменты модерации',
    'auth.operatorNote': 'Расписание и операции прогнозирования',
    'auth.userNote': 'История, сохраненные запуски и просмотр',
    'auth.enterPassword': 'Введите пароль',
    'auth.createPassword': 'Создайте надежный пароль',
    'auth.signInHint': 'Используйте email или короткий демо-алиас, например admin, operator или user.',
    'auth.registerHint': 'Регистрация создает реального пользователя в бэкенде и сразу запускает живую сессию.',
    'auth.demoHint': 'Демо-алиасы работают и здесь: введите admin, operator или user вместо полного email.',
    'auth.newAccountHint': 'Новые аккаунты создаются со стандартной ролью пользователя и могут сразу сохранять прогнозы.',
    'auth.invalidCredentials': 'Неверные учетные данные. Попробуйте один из демо-аккаунтов ниже.',
    'auth.registrationFailed': 'Регистрация не может быть завершена.',
    'auth.authFailed': 'Ошибка аутентификации.',

    // Features
    'feature.history': 'Постоянная история прогнозов',
    'feature.historyDesc': 'Каждый запуск привязан к активному аккаунту и отображается в приватной ленте истории.',
    'feature.workspace': 'Ролевой доступ к рабочему пространству',
    'feature.workspaceDesc': 'Сессии администратора, оператора и пользователя открывают разные части платформы.',
    'feature.auth': 'Живая бэкенд-аутентификация',
    'feature.authDesc': 'Экран взаимодействует с реальным Node API и сессиями Postgres, а не с фиктивной фронтенд-формой.',

    // Home page
    'home.title': 'Более чистая аналитика матчей, меньше шума на главной странице.',
    'home.subtitle': 'Главный экран теперь работает как спортивный хаб: сначала ключевые метрики, затем текущий матч, а остальная информация разделена на более четкие секции вместо одной длинной декоративной ленты.',
    'home.connected': 'Подключенный стек',
    'home.liveBasketball': 'Живое баскетбольное пространство',
    'home.newPrediction': 'Новый прогноз',
    'home.openSchedule': 'Открыть расписание',
    'home.featuredGame': 'Избранная игра',
    'home.preview': 'Превью',
    'home.final': 'Финал',
    'home.noGame': 'Нет загруженных игр',
    'home.modelConfidence': 'Уверенность модели',
    'home.nextFixture': 'Здесь появится следующая загруженная игра.',
    'home.accuracy': 'Точность',
    'home.teams': 'Команды',
    'home.games': 'Игры',
    'home.samples': 'Сэмплы',
    'home.modelValidation': 'валидация модели',
    'home.trackedProfiles': 'отслеживаемые профили',
    'home.loadedFixtures': 'загруженные матчи',
    'home.historicalRecords': 'исторические записи',
    'home.notes': 'Заметки',
    'home.predictionEngine': 'Движок прогнозирования',
    'home.predictionEngineDesc': 'Размер исторической выборки стабилен, и эндпоинт прогнозирования отвечает через живой бэкенд.',
    'home.scheduleWindow': 'Текущее окно расписания',
    'home.scheduleWindowDesc': '{upcoming} предстоящих игр и {recent} завершенных игр доступны для просмотра.',
    'home.navigationCleanup': 'Очистка навигации',
    'home.navigationCleanupDesc': 'Вместо вертикального размещения всего контента, главная страница теперь разделяет расписание, команды и прогнозы по вкладкам.',
    'home.standingsSnapshot': 'Снимок таблицы',
    'home.topTeams': 'Лучшие команды',
    'home.fullStandings': 'Полная таблица',
    'home.overview': 'Обзор',
    'home.schedule': 'Расписание',
    'home.predictions': 'Прогнозы',
    'home.recentUpcoming': 'Недавние и предстоящие игры',
    'home.allGames': 'Все игры',
    'home.teamBoard': 'Доска команд',
    'home.leagueLeaders': 'Лидеры лиги',
    'home.teamIndex': 'Индекс команд',
    'home.predictionLane': 'Линия прогнозов',
    'home.recentRuns': 'Недавние запуски модели',
    'home.predictionWorkspace': 'Рабочее пространство прогнозов',
    'home.history': 'История',
    'home.noPredictions': 'Вы еще не сохранили ни одного прогноза. Начните с матча, и результат появится здесь и в истории.',
    'home.signInPrompt': 'Войдите, чтобы сохранять прогнозы, просматривать результаты и сравнивать выводы модели с течением времени.',

    // Teams page
    'teams.title': 'Турнирная таблица и идентичность команд в одной компактной доске.',
    'teams.subtitle': 'Быстро сравнивайте команды в виде таблицы, затем переключайтесь на карточки для более детального просмотра.',
    'teams.board': 'Доска команд',
    'teams.clubsLoaded': '{count} клубов загружено',
    'teams.searchTeams': 'Поиск команд',
    'teams.searchPlaceholder': 'Бостон, Атлантик, BOS...',
    'teams.view': 'Вид',
    'teams.standings': 'Таблица',
    'teams.cards': 'Карточки',
    'teams.conference': 'Конференция',
    'teams.all': 'Все',
    'teams.east': 'Восток',
    'teams.west': 'Запад',
    'teams.topRecord': 'Лучший результат',
    'teams.leagueOffense': 'Атака лиги',
    'teams.bestDifferential': 'Лучшая разница',
    'teams.visibleTeams': 'Видимые команды',
    'teams.noData': 'Нет данных',
    'teams.averageAcross': 'Среднее по всем командам.',
    'teams.netPoints': '{value} чистая разница',
    'teams.withinView': 'В текущем представлении.',
    'teams.rank': 'Место',
    'teams.team': 'Команда',
    'teams.record': 'Рекорд',
    'teams.winRate': 'Победы %',
    'teams.for': 'За',
    'teams.allowed': 'Против',
    'teams.net': 'Разн',
    'teams.division': 'Дивизион',

    // Players page
    'players.title': 'Профили игроков с переключателем сезонов',
    'players.subtitle': 'Нажмите на любую карточку, чтобы открыть полный профиль с возможностью переключения между сезонами.',
    'players.searchPlaceholder': 'Леброн, Карри, Йокич...',
    'players.view': 'Вид',
    'players.cards': 'Карточки',
    'players.board': 'Доска',
    'players.topScorer': 'Лучший бомбардир',
    'players.topPlaymaker': 'Лучший плеймейкер',
    'players.averageScoring': 'Средняя результативность',
    'players.acrossSet': 'По текущей выборке.',
    'players.clickPrompt': 'Нажмите на карточку для открытия профиля с переключателем сезонов.',
    'players.player': 'Игрок',
    'players.team': 'Команда',
    'players.position': 'Поз',
    'players.openProfile': 'Открыть профиль',

    // Matches page
    'matches.title': 'Расписание и результаты в одном компактном представлении.',
    'matches.subtitle': 'Просматривайте список, открывайте игру для контекста или переходите к прогнозированию без борьбы с макетом.',
    'matches.board': 'Доска матчей',
    'matches.gamesInFeed': '{count} игр в ленте',
    'matches.filter': 'Фильтр',
    'matches.allGames': 'Все игры',
    'matches.upcoming': 'Предстоящие',
    'matches.finals': 'Завершенные',
    'matches.currentFocus': 'Текущий фокус',
    'matches.allDesc': 'Показаны все матчи: завершенные и предстоящие.',
    'matches.upcomingDesc': 'Показаны только предстоящие игры, готовые к превью и прогнозам.',
    'matches.finalsDesc': 'Показаны финальные результаты для быстрого просмотра и сравнения.',
    'matches.finished': 'Завершено',
    'matches.finishedDesc': 'Игры с финальным счетом.',
    'matches.upcomingCount': 'Предстоит',
    'matches.upcomingCountDesc': 'Матчи, готовые к превью.',
    'matches.currentView': 'Текущий вид',
    'matches.selectedBoard': 'Выбранное состояние доски.',
    'matches.visibleGames': 'Видимые игры',
    'matches.listedBelow': 'Отображаются ниже.',
    'matches.date': 'Дата',
    'matches.matchup': 'Матч',
    'matches.status': 'Статус',
    'matches.score': 'Счет',
    'matches.final': 'Финал',
    'matches.scheduled': 'Запланирован',
    'matches.openDetail': 'Открыть детали',
    'matches.noMatches': 'Нет игр, соответствующих фильтру.',

    // Match detail page
    'match.backToSchedule': 'Назад к расписанию',
    'match.finalScore': 'Финальный счет',
    'match.upcomingFixture': 'Предстоящий матч',
    'match.scoreline': 'Счет',
    'match.useAI': 'Использовать AI для этого матча',
    'match.useAIDesc': 'Запустите вероятностный анализ, используя текущую форму команд и историческую базу сигналов, уже загруженную в бэкенд.',
    'match.createPrediction': 'Создать прогноз',
    'match.notFound': 'Матч не найден.',
    'match.backToMatches': 'Назад к матчам',

    // Analytics page
    'analytics.title': 'Единое аналитическое пространство, разделенное на более четкие операционные представления.',
    'analytics.subtitle': 'Качество модели, контекст лиги и поведение расписания теперь находятся в отдельных разделах, поэтому страница читается больше как внутренняя консоль и меньше как стена виджетов.',
    'analytics.board': 'Панель аналитики',
    'analytics.loading': 'Загрузка аналитической ленты',
    'analytics.views': 'Представления',
    'analytics.model': 'Модель',
    'analytics.league': 'Лига',
    'analytics.schedule': 'Расписание',
    'analytics.modelDesc': 'Представление модели фокусируется на здоровье, смеси факторов и покрытии базы данных.',
    'analytics.leagueDesc': 'Представление лиги выделяет претендентов, атакующую продуктивность и сравнительный контекст команд.',
    'analytics.scheduleDesc': 'Представление расписания показывает нагрузку игр и недавно отслеживаемые матчи.',
    'analytics.topTeam': 'Лучшая команда',
    'analytics.loadedGames': 'Загруженные игры',
    'analytics.trackedPlayers': 'Отслеживаемые игроки',
    'analytics.modelHealth': 'Здоровье модели',
    'analytics.predictionAccuracy': 'Точность прогнозов',
    'analytics.historicalDepth': 'Глубина исторических данных',
    'analytics.rosterCoverage': 'Покрытие состава',
    'analytics.scheduleReadiness': 'Готовность расписания',
    'analytics.modelVersion': 'Версия модели',
    'analytics.teamsConnected': 'Подключено команд',
    'analytics.signalsTracked': 'Отслеживается сигналов',
    'analytics.healthSnapshot': 'Снимок здоровья',
    'analytics.factorDistribution': 'Распределение факторов модели',
    'analytics.contenderBoard': 'Доска побед претендентов',
    'analytics.offensiveOutput': 'Атакующая продуктивность лучших команд',
    'analytics.scheduleIntensity': 'Интенсивность расписания по загруженным матчам',
    'analytics.unavailable': 'Недоступно',

    // Prediction pages
    'prediction.buildMatchup': 'Создайте матч и позвольте модели работать с реальным контекстом команд.',
    'prediction.engine': 'Движок матчей',
    'prediction.teamsAvailable': '{count} команд доступно',
    'prediction.historicalContext': 'Исторические данные, текущая форма, качество состава и контекст матча теперь объединяются через живой движок прогнозирования.',
    'prediction.preview': 'Превью',
    'prediction.homeSide': 'Домашняя сторона',
    'prediction.awaySide': 'Гостевая сторона',
    'prediction.selectTeam': 'Выберите команду',
    'prediction.waitingSelection': 'Ожидание выбора',
    'prediction.chooseHome': 'Выберите домашнюю команду',
    'prediction.chooseAway': 'Выберите гостевую команду',
    'prediction.pickBoth': 'Выберите обе команды перед запуском модели.',
    'prediction.differentTeams': 'Выберите две разные команды.',
    'prediction.savedToAccount': 'Прогноз сохраняется в вашем аккаунте и сразу оценивается гибридной моделью.',
    'prediction.generate': 'Сгенерировать прогноз',
    'prediction.running': 'Запуск модели...',
    'prediction.signInRequired': 'Войдите для создания приватных прогнозов.',
    'prediction.signInDesc': 'Прогнозы сохраняются за реальными учетными записями, поэтому вам нужна аутентифицированная сессия, прежде чем модель сможет сохранить и вернуть результат.',
    'prediction.unlock': 'Разблокировать режим прогнозов',
    'prediction.backToBuilder': 'Назад к конструктору прогнозов',
    'prediction.notFound': 'Прогноз не найден.',
    'prediction.missingId': 'ID прогноза отсутствует.',
    'prediction.aiResult': 'AI результат',
    'prediction.confidence': '{value}% уверенность',
    'prediction.modelLeans': 'Модель склоняется к {team} на основе текущего профиля команды, живых сигналов состава и обученной смеси исторических сигналов.',
    'prediction.trainingRows': '{count} строк обучения',
    'prediction.expectedScore': 'Ожидаемый счет',
    'prediction.modelSplit': 'Разделение модели',

    // History page
    'history.title': 'Ваша история прогнозов.',
    'history.subtitle': 'Каждый запуск привязан к вашему аккаунту и доступен для быстрого просмотра в приложении.',
    'history.savedRuns': 'Сохраненные запуски прогнозов',
    'history.items': '{count} элементов',
    'history.signInRequired': 'Ваша история станет доступна после входа.',
    'history.signInDesc': 'История прогнозов привязана к аутентифицированным аккаунтам и хранится в подключенной базе данных.',
    'history.signIn': 'Войти',
    'history.noPredictions': 'Вы еще не создали ни одного прогноза.',
    'history.startNew': 'Начать новый запуск',

    // Admin page
    'admin.title': 'Инструменты администратора, сгруппированные в более чистую панель управления.',
    'admin.subtitle': 'Пользователи, аудит и резервные копии находятся в отдельных операционных представлениях, что делает модерацию и обслуживание более компактными и удобными для сканирования.',
    'admin.restricted': 'Ограниченное рабочее пространство',
    'admin.createBackup': 'Создать резервную копию',
    'admin.creatingBackup': 'Создание резервной копии...',
    'admin.reviewUsers': 'Просмотр пользователей',
    'admin.systemSnapshot': 'Снимок системы',
    'admin.modelAccuracy': 'Точность модели',
    'admin.backupsStored': 'Сохранено копий',
    'admin.lastBackup': 'Последняя копия',
    'admin.noBackups': 'Нет резервных копий',
    'admin.overview': 'Обзор',
    'admin.users': 'Пользователи',
    'admin.auditLog': 'Журнал аудита',
    'admin.backups': 'Резервные копии',
    'admin.stackStatus': 'Состояние стека',
    'admin.teamsTracked': 'Отслеживается команд',
    'admin.matchesTracked': 'Отслеживается матчей',
    'admin.playersTracked': 'Отслеживается игроков',
    'admin.predictionsTracked': 'Отслеживается прогнозов',
    'admin.quickActions': 'Быстрые действия',
    'admin.createNewBackup': 'Создать новую копию',
    'admin.openAuditLog': 'Открыть журнал аудита',
    'admin.activeAccounts': 'Активные аккаунты',
    'admin.blockedAccounts': 'Заблокированные аккаунты',
    'admin.user': 'Пользователь',
    'admin.role': 'Роль',
    'admin.status': 'Статус',
    'admin.action': 'Действие',
    'admin.active': 'Активен',
    'admin.blocked': 'Заблокирован',
    'admin.block': 'Заблокировать',
    'admin.unblock': 'Разблокировать',
    'admin.updating': 'Обновление...',
    'admin.noUsers': 'Бэкенд не вернул пользователей.',
    'admin.auditTimeline': 'Временная шкала аудита',
    'admin.noEvents': 'Бэкенд не вернул событий аудита.',
    'admin.noDetails': 'Дополнительные детали не записаны.',
    'admin.actor': 'Инициатор',
    'admin.backupOperations': 'Операции с резервными копиями',
    'admin.backupOpsDesc': 'Создавайте восстанавливаемые снимки напрямую через подключенный API администратора.',
    'admin.createNewBackup': 'Создать новую резервную копию',
    'admin.noBackupsAvailable': 'Резервные копии в настоящее время недоступны.',
    'admin.backup': 'Резервная копия',
    'admin.size': 'Размер',
    'admin.restore': 'Восстановить',
    'admin.restoring': 'Восстановление...',
    'admin.confirmRestore': 'Восстановить {filename}? Это перезапишет текущее содержимое базы данных.',
    'admin.backupCreated': 'Резервная копия создана: {filename}',
    'admin.backupFailed': 'Создание резервной копии не удалось.',
    'admin.backupRestored': 'Резервная копия восстановлена: {filename}',
    'admin.restoreFailed': 'Восстановление резервной копии не удалось.',
    'admin.userStatusUpdated': '{username} теперь {status}.',
    'admin.statusUpdateFailed': 'Обновление статуса пользователя не удалось.',
    'admin.loadFailed': 'Не удалось загрузить данные администратора с бэкенда.',

    // 404 page
    'notfound.title': 'Эта страница вне доски.',
    'notfound.subtitle': 'Запрошенный маршрут недоступен в текущей сборке. Вернитесь на дашборд или перейдите в разделы скаутинга, которые уже подключены к живому стеку.',
    'notfound.backToDashboard': 'Назад к дашборду',
    'notfound.exploreTeams': 'Исследовать команды',
    'notfound.routeMissing': '404 • маршрут отсутствует',

    // Footer
    'footer.copyright': '© 2026 Score Team',
    'footer.subscribe': 'Подписывайтесь на нас',
    'footer.copied': 'Скопировано!',
    'footer.email': 'Email',

    // Common
    'common.loading': 'Загрузка дашборда',
    'common.signIn': 'Войти',
    'common.unavailable': 'Недоступно',
    'common.home': 'Дом',
    'common.away': 'Гости',
    'common.vs': 'Против',
    'common.tipoff': 'Начало',

    // Season
    'season.n_a': 'Сезон н/д',
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved === 'ru' ? 'ru' : 'en') as Language;
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'ru' : 'en');
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, toggleLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used inside LanguageProvider');
  }
  return context;
};